version: '3.8'

x-processor: &processor
  build: .
  command: yarn start
  container_name: ym-image-processor
  restart: unless-stopped
  deploy:
    resources:
      limits:
        memory: 3g
  networks:
    - coolify

services:
  paradis:
    <<: *processor
    command: yarn start:server
    container_name: paradis-ym

  maria:
    <<: *processor
    container_name: maria-ym
    environment:
      - PROCESSOR_NAME=Maria

  rose:
    <<: *processor
    container_name: rose-ym
    environment:
      - PROCESSOR_NAME=Rose

  sina:
    <<: *processor
    container_name: sina-ym
    environment:
      - PROCESSOR_NAME=Sina

networks:
  coolify:
    external: true
